export const styles = {
	yMargin: "my-8 md:my-16",
	icon: "hover:text-primary transition-colors duration-300 ease-in-out hover:scale-110",
	link: "hover:text-primary transition-colors duration-300 ease-in-out hover:scale-110",
	button: "bg-primary text-white hover:bg-primary/90 transition-colors duration-300 ease-in-out hover:scale-110",
	buttonOutline: "bg-transparent border-2 border-primary text-primary hover:bg-primary hover:text-white transition-colors duration-300 ease-in-out hover:scale-110",
	buttonSecondary: "bg-secondary text-white hover:bg-secondary/90 transition-colors duration-300 ease-in-out hover:scale-110",
	buttonSecondaryOutline: "bg-transparent border-2 border-secondary text-secondary hover:bg-secondary hover:text-white transition-colors duration-300 ease-in-out hover:scale-110",
	heading: "text-2xl font-bold",
	h1: "text-4xl font-bold",
	h2: "text-3xl font-bold",
	h3: "text-2xl font-bold",
	h4: "text-xl font-bold",
	h5: "text-lg font-bold",
	h6: "text-base font-bold",
	subheading: "text-xl font-semibold",
	paragraph: "text-base",
	section: "py-6",
	small: "text-sm",
	tiny: "text-xs",
	caption: "text-xs",
	label: "text-sm font-semibold",
	placeholder: "text-gray-500",
	disabled: "opacity-50 cursor-not-allowed",
	active: "text-primary",
	hover: "hover:text-primary",
	focus: "focus:text-primary",
	visited: "visited:text-primary",
	image: "w-full h-full object-contain rounded-xl",
	siteTitle: "font-bold tracking-widest leading-tight",
	siteTitleGradient: "gradient-text",
	gradientLength: 7,
	hero: {
		main: "hero-content relative mx-auto pt-24 flex flex-col gap-4 lg:flex-row items-center justify-between",
		textArea: "lg:w-1/2 text-center lg:text-left mb-12 lg:mb-0",
		header: "text-6xl md:text-7xl lg:text-7xl font-bold leading-tight flex items-start gap-4 text-left",
		subheader: "text-xl mb-8 text-left",
		button: "btn btn-primary",
		buttonOutline: "btn btn-outline btn-primary",
		buttonSecondary: "btn btn-outline btn-secondary",
		image: "rounded-lg",
	},
	blur: "absolute h-[75vh] w-[75vw] rounded-full animate-gradient-xy filter blur-3xl opacity-5",
	blurColor: "bg-gradient-to-r from-blue-500 to-blue-800",
	// image: "rounded-xl absolute top-0 left-0 w-full h-full",
};
